name: build
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    lemon_deploy_font_end:
        name: lemon
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: install depth then build
              run: |
                  npm i
                  npm run build
            - name: show folders
              run: ls
            - name: upload serve
              uses: SamKirkland/FTP-Deploy-Action@2.0.0
              env:
                  FTP_SERVER: ${{ secrets.FTP_IP }}
                  FTP_USERNAME: ${{ secrets.FTP_USER_NAME }}
                  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
                  METHOD: sftp
                  LOCAL_DIR: build
                  REMOTE_DIR: /usr/local/docker/nginx/html
                  ARGS: --delete

    GIT-Tags:
        needs: [lemon_deploy_font_end]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: Klemensas/action-autotag@stable
              with:
                  GITHUB_TOKEN: '${{ secrets.DE_TO }}'
                  tag_prefix: 'v'
