name: 构建与发布
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    lemon-Deploy-Action:
        name: Tomokotv-Deploy-Action
        runs-on: ubuntu-latest
        steps:
            - name: 克隆下载
            - uses: actions/checkout@v2

            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: 安装依赖并构建
              run: |
                  npm i
                  npm run build
            - name: 查看文件目录
              run: ls
            - name: 上传到服务器
              uses: SamKirkland/FTP-Deploy-Action@2.0.0
              env:
                  FTP_SERVER: ${{ secrets.FTP_IP }}
                  FTP_USERNAME: ${{ secrets.USER_NAME }}
                  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
                  METHOD: sftp
                  LOCAL_DIR: build
                  REMOTE_DIR: /usr/share/nginx/html
                  ARGS: --delete
    GIT-Tags:
        needs: lemon-Deploy-Action
        build:
            runs-on: ubuntu-latest
            steps:
                - name: 克隆下载
                - uses: actions/checkout@v2
                - uses: Klemensas/action-autotag@stable
                  with:
                      GITHUB_TOKEN: '${{ secrets.DE_TO }}'
                      tag_prefix: 'v'
